<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>6d72d3d1-56bc-4f90-a462-8ef25baf9b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mt-4.btn.btn-primary.text-white.d-flex.justify-content-center.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>911ddb0a-d9a1-4b86-8f51-c177ea4f7198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4d15f839-d410-4759-a28b-79b5b4012a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 btn btn-primary text-white d-flex justify-content-center align-items-center</value>
      <webElementGuid>0ba62bc2-bb1f-43da-923c-21c8051cfeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Login
                                </value>
      <webElementGuid>61907347-b5c9-415a-8b26-8b047aea7eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;body d-md-flex align-items-center&quot;]/div[@class=&quot;box-2 d-flex flex-column&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;card-mobile d-flex flex-column&quot;]/div[@class=&quot;input-field d-flex flex-column&quot;]/form[@class=&quot;form-horizontal&quot;]/button[@class=&quot;mt-4 btn btn-primary text-white d-flex justify-content-center align-items-center&quot;]</value>
      <webElementGuid>4e3fea5c-73eb-4781-b7ff-09282fb820be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e66b9e3a-5f85-41e0-b521-96d1a9868c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/div/div/div[2]/div/div/div/form/button</value>
      <webElementGuid>8b20d719-9d29-441f-94e1-823a34bc7139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Password'])[1]/preceding::button[1]</value>
      <webElementGuid>e20be1cc-f292-4279-a5ed-f0023bb5d911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password ?'])[1]/preceding::button[1]</value>
      <webElementGuid>62d8d75e-ebbd-4507-bdec-9872130dc770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>9966fa5b-5585-4e82-9f1e-3b60548f7e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>13afbb45-4d5e-4146-9dfd-fa21e80f4c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                    Login
                                ' or . = '
                                    Login
                                ')]</value>
      <webElementGuid>ee3b6b7b-a802-4112-afb8-ada1d11c0efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
