<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Konversi Kuliah Mahasiswa_fas fa-refresh</name>
   <tag></tag>
   <elementGuidId>b632999e-609b-46c1-846b-c048d55337b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='syncButton']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sinkronisasi Siakadu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>62a8319d-7709-487b-8ce0-09a59580ec5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-refresh</value>
      <webElementGuid>352cf0da-21bd-4b44-a0c7-70b32cd3e230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;syncButton&quot;)/i[@class=&quot;fas fa-refresh&quot;]</value>
      <webElementGuid>5d705305-1468-4d66-9b6b-28a81aa7076a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='syncButton']/i</value>
      <webElementGuid>91a0f8ac-5d9c-4347-b809-eecb6407a9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/i</value>
      <webElementGuid>d5a72962-2dc8-48b0-83bb-f8181bc04bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
