<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Konversi Kuliah Mahasiswa_fas fa-lock</name>
   <tag></tag>
   <elementGuidId>92b41028-c168-4883-8853-c7321868f220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='simpanButton']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-lock</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Simpan Permanen&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2e2bde18-2e0f-42b1-90d2-03f519fae846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-lock</value>
      <webElementGuid>f39f5153-7975-4145-b6c6-a0528abf93d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simpanButton&quot;)/i[@class=&quot;fas fa-lock&quot;]</value>
      <webElementGuid>b1129265-b7d1-4be7-a781-14c601fa3cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='simpanButton']/i</value>
      <webElementGuid>4285a963-3f3d-4635-815a-7bbede96d49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>7ea3c75a-e1cd-423b-b8e7-dfeaea56d69a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
