<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Konversi Kuliah Mahasiswa_fas fa-print</name>
   <tag></tag>
   <elementGuidId>44f5bac9-09c7-467a-9fa2-661bbce50dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cetakButton']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-print</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cetak LA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2ac00d35-fa68-4352-8049-7001d6a49bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-print</value>
      <webElementGuid>c937e882-ba93-490b-bd70-80dcdb1ed93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cetakButton&quot;)/i[@class=&quot;fas fa-print&quot;]</value>
      <webElementGuid>4d2eda0e-40d3-4532-bc7f-7bc7c917c372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cetakButton']/i</value>
      <webElementGuid>f2bf3d6b-5f11-418b-966d-2808863c62f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>2776a0b3-8ed2-4521-8c9e-e53a2c0f3ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
